(define memories
  '((memory flash (address (#x10000 . #x1ffff))
            (section farcode idata cdata switch))
    (memory LoRAM (address (#x4000 . #xefff))
            (section stack data zdata heap))
    (memory NearRAM (address (#x20000 . #x21ffff))
            (section znear))
    (memory FarRAM (address (#x30000 . #x3ffff))
            (section far zfar cfar))
    (memory DirectPage (address (#xf000 . #xf0ff))
            (section (registers ztiny)))
    (memory Vector (address (#xff00 . #xffff))
            (section (reset #xfffc)))
    (memory LoCode (address (#xf100 . #xfeff))
            (section code cdata data_init_table))
    (block stack (size #x1000))
    (block heap (size #x1000))
    (base-address _DirectPageStart DirectPage 0)
    (base-address _NearBaseAddress NearRAM    0)
    ))
