; Generated by Calypsi ISO C compiler for 65816

            .rtmodel version,"1"
            .rtmodel codeModel,"large"
            .rtmodel dataModel,"large"
            .rtmodel core,"65816"
            .rtmodel huge,"0"
            .rtmodel target,"atari"
            .extern _DirectPageStart
            .extern _Dp
            .extern _NearBaseAddress
            .extern _Vfp
;  #include "cpx.h"
;  static CPXINFO info;
            .section zfar,bss
info:       .space  40
;  CPX_ENTRY CPXINFO FAR *cpx_init(XCPB FAR *pb) { (void)pb; return &info; }
            .section farcode,text
            .public cpx_init
cpx_init:   phb
            phd
            lda     ##_DirectPageStart
            tcd
            lda     ##.word2 _NearBaseAddress
            xba
            pha
            plb
            plb
            lda     ##.word0 info
            ldx     ##.word2 info
            pld
            plb
            rtl

