; mscan_b12.s -- B12's shape, cc65816 5.18.2 -O1, the compiler's own assembly for two
; functions: hi_nibble, a signed 16-bit >> 4 that sign-extends a FOUR-bit field
; (one hit), and hi_nibble_ok, the same shift unsigned (silent).  The fixture that
; proves mscan.wrong_bit() can report (tools/ccbug/README.md, B12).
; Generated by Calypsi ISO C compiler for 65816

            .rtmodel version,"1"
            .rtmodel codeModel,"large"
            .rtmodel dataModel,"small"
            .rtmodel core,"65816"
            .rtmodel huge,"0"
            .rtmodel target,"none-specified"
            .extern _Dp
            .extern _Vfp
;  #include <stdint.h>
;  /* B12: a signed 16-bit >> 4 of a zero-extended byte.  0xFF must give 15. */
;  int16_t hi_nibble(const uint8_t *b) { int16_t byte = b[0]; return byte >> 4; }
            .section farcode,text
            .public hi_nibble
hi_nibble:  tax
            lda     0,x
            and     ##255
            lsr     a
            lsr     a
            lsr     a
            lsr     a
            eor     ##8
            and     ##15
            sec
            sbc     ##8
            rtl
;  /* ...and the control, which must stay silent: the same shift unsigned. */
;  int16_t hi_nibble_ok(const uint8_t *b) { uint16_t byte = b[0]; return (int16_t)(byte >> 4); }
            .section farcode,text
            .public hi_nibble_ok
hi_nibble_ok:
            tax
            lda     0,x
            and     ##255
            lsr     a
            lsr     a
            lsr     a
            lsr     a
            rtl

