"""gem4xe's own desktop icons, in colour: the art.

tools/deskiconrsc.py makes build/deskicon.rsc from these, shipped as
GEM>DESKICON.RSC beside DESKTOP.RSC; the desktop draws its six kinds of
icon from it (src/desk/desktop.c, desk_cicons; docs/phase89.md).  A
Falcon's own DESKICON.RSC copied over it works the same way.

Each icon is 32 rows of 32 characters, one character a pixel, in the
GEM desktop's sixteen VDI pens (src/vdi/vdi.c, gem_rgb):

    W white   K black   r red        G green      b blue      c cyan
    y yellow  m magenta g light grey d dark grey  R dark red  n dark green
    B dark blue  C dark cyan  Y dark yellow  M dark magenta   . clear

The mask is every pixel that is not '.'.  The mono form, for a two-colour
screen, and the selected form are worked out from the colours by the
generator, so this file is the only place the pictures are drawn.

DRAWN FOR TALL PIXELS.  On the 640x240 screen a pixel is about twice as
tall as it is wide, so a picture that is square on the TV is twice as
wide as it is tall here: the 5.25" disk is 28 x 16.  Each sits at the
bottom of the desktop's 32 x 32 cell, which keeps the desktop's grid --
and a Falcon's DESKICON.RSC, drawn 32 x 32 for square pixels -- as they
were.  (The Falcon's look tall and narrow here, as EmuTOS's do.)

The digit, for a drive, is (x, y, pen): where the desktop draws the
drive's number (the ICONBLK's ib_xchar, ib_ychar), from the 8x8 font,
and in which pen.  It is black on white, on both drives, and has to be:
the colour form's mask goes down in the ICONBLK's background colour
before the image is ORed over it, so a black background would leave
the whole icon black, and the mono form is drawn in the digit's colour.
"""

# (label, what it is, the digit or None, the rows); the label is what
# the desktop finds an icon by, spaces and case aside
ICONS = [
    ("HARD DISK", "a CompactFlash card: SIDE, IDE+ and the rest", (8, 17, 'K'), [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "....KKKKKKKKKKKKKKKKKKKKKKKK....",
        "....KggggggggggggggggggggggK....",
        "....KgdKKKKKKKKKKKKKKKKKKddK....",
        "....KgdKWWWWWWWWWWWWWWWWKddK....",
        "....KgdKWWWWWWWWWbbbbbbWKddK....",
        "....KgdKWWWWWWWWWWWWWWWWKddK....",
        "....KgdKWWWWWWWWWBBBBBBWKddK....",
        "....KgdKWWWWWWWWWWWWWWWWKddK....",
        "....KgdKWWWWWWWWWbbbbbWWKddK....",
        "....KgdKWWWWWWWWWWWWWWWWKddK....",
        "....KgdKWWWWWWWWWWWWWWWWKddK....",
        "....KgdKKKKKKKKKKKKKKKKKKddK....",
        "....KgdddddddddddddddddddddK....",
        "....KgddrrrrrrrrrrrrrrrrdddK....",
        "....KgdddddddddddddddddddddK....",
        "....KgYdYdYdYdYdYdYdYdYdYddK....",
        "....KgYdYdYdYdYdYdYdYdYdYddK....",
        "....KKKKKKKKKKKKKKKKKKKKKKKK....",
    ]),
    ("FLOPPY DISK", "a 5.25-inch diskette, the A8's", (6, 18, 'K'), [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
        "..KdKKKKKKKKKKKddddddddddddddK..",
        "..KdKWWWWWWWWWKKKKKKKKKKKKKKK...",
        "..KdKWWWWWWWWWKKKKKKKKKKKKKKK...",
        "..KdKWWWWWWWWWKKKWKKKKKKKKKKKK..",
        "..KdKWWWWWWWWWKKKKKKgggggKKKKK..",
        "..KdKWWWWWWWWWKKKKgggggggggKKK..",
        "..KdKWWWWWWWWWKKKgggWWWWWgggKK..",
        "..KdKWWWWWWWWWKKKgggWWWWWgggKK..",
        "..KdKWWWWWWWWWKKKKgggggggggKKK..",
        "..KdKWbbbbbbbWKKKKKKgggggKKKKK..",
        "..KdKKKKKKKKKKKKKKKKKKKKKKKKKK..",
        "..KdKKKKKKKKKKKKKKKKKKKKKKKKKK..",
        "..KdKKKKKKKKKKKKKKKKdddddKKKKK..",
        "..KdKKKKKKKKKKKKKKKKdddddKKKKK..",
        "..KKKKKKKKKKKKKKKKKKdddddKKKKK..",
    ]),
    ("TRASH CAN", "a metal bin", None, [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............KKKKKK.............",
        ".............K....K.............",
        ".....KWWWWWWWWWWWWWWWWWWWWK.....",
        ".....KKKKKKKKKKKKKKKKKKKKKK.....",
        ".......KKKKKKKKKKKKKKKKKK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KggdWggdWggdWggdgK.......",
        ".......KKKKKKKKKKKKKKKKKK.......",
    ]),
    ("FOLDER", "a yellow folder", None, [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "..KKKKKKKKKKK...................",
        "..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyyK..",
        "..KYYYYYYYYYYYYYYYYYYYYYYYYYYK..",
        "..KWWWWWWWWWWWWWWWWWWWWWWWWWYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KyyyyyyyyyyyyyyyyyyyyyyyyyYK..",
        "..KYYYYYYYYYYYYYYYYYYYYYYYYYYK..",
        "..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
    ]),
    ("PROGRAM FILE", "an Atari cartridge", None, [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".....KKKKKKKKKKKKKKKKKKKKKK.....",
        ".....KWWWWWWWWWWWWWWWWWWWWK.....",
        ".....KWggggggggggggggggggdK.....",
        ".....KWgKKKKKKKKKKKKKKKKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKWrrRRyyYYbbBBWKgdK.....",
        ".....KWgKKKKKKKKKKKKKKKKgdK.....",
        ".....KWggggggggggggggggggdK.....",
        ".....KWggggggggggggggggggdK.....",
        ".....KWggggggggggggggggggdK.....",
        ".....KWggggggggggggggggggdK.....",
        ".....KKKKKKKKKKKKKKKKKKKKKK.....",
        ".......KnynynynynynynynnK.......",
        ".......KnynynynynynynynnK.......",
        ".......KnynynynynynynynnK.......",
        ".......KKKKKKKKKKKKKKKKKK.......",
    ]),
    ("TEXT FILE", "a page with its corner turned", None, [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "........KKKKKKKKKKKKK...........",
        "........KWWWWWWWWWWKgKK.........",
        "........KWBBBBBBBBWKgggK........",
        "........KWWWWWWWWWWKKKKK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBBBBBWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBBBBWWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBBBBBWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBWWWWWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBBBBWWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBBWWWWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KWBBBBBBBBBBWWWK........",
        "........KWWWWWWWWWWWWWWK........",
        "........KKKKKKKKKKKKKKKK........",
    ]),
]
