#!/usr/bin/env python3
"""Host reference implementation of the gem4xe VDI.

This is the SPECIFICATION.  src/vdi/vdi.c must agree with it byte for byte on
every script the conformance suite runs; when they disagree, this one is right
until proven otherwise, and the disagreement gets shrunk into a new case.

It models the same blit-list strategy the target uses -- including the AND/OR
pair that handles a 4bpp rectangle's odd-pixel edges -- so a mismatch points at
a real difference in behaviour rather than at two unrelated rasterisers.
"""
import math
import os
import re
import zlib

import devref
import fontref
import vbxeref

# THE VBXE's geometry, for the one thing left in this file that is about
# that device: VramForm, the AES's save buffer in VRAM.  The RASTERISER
# below does not use them -- it reads self.dev (tools/devref.py), the
# way src/vdi/vdi.c reads `vdev`.
# The DEFAULT screen, for the callers that have nothing to say about it.
# A model drawing at another width takes it from its device (vdi.dev.w),
# which is where the width actually lives -- see tools/vbxeref.py.
SCR_W, SCR_H, STRIDE = vbxeref.SCR_W, vbxeref.SCR_H, vbxeref.STRIDE

# opcodes
V_OPNWK, V_CLSWK, V_CLRWK, V_PLINE = 1, 2, 3, 6
VSL_TYPE, VSL_WIDTH, VSL_COLOR = 15, 16, 17
VST_COLOR, VSF_INTERIOR, VSF_STYLE, VSF_COLOR = 22, 23, 24, 25
VSWR_MODE = 32
V_OPNVWK, V_CLSVWK, VQ_EXTND = 100, 101, 102
VRO_CPYFM, VR_TRNFM, VR_RECFL, VS_CLIP = 109, 110, 114, 129
V_GTEXT = 8
VRT_CPYFM = 121
VSC_FORM, V_SHOW_C, V_HIDE_C, VQ_MOUSE = 111, 122, 123, 124
VSIN_MODE, VQIN_MODE, VEX_TIMV, VSL_UDSTY = 33, 115, 118, 113
VEX_BUTV, VEX_MOTV = 125, 126
VST_HEIGHT, VQT_ATTRIBUTES, V_ESCAPE = 12, 38, 5
VST_FONT, VST_LOAD_FONTS, VST_UNLOAD_FONTS, VQT_NAME = 21, 119, 120, 130
VS_COLOR, VQ_COLOR, VST_ALIGNMENT = 14, 26, 39
VST_EFFECTS, VST_POINT, VQT_EXTENT, VQT_WIDTH = 106, 107, 116, 117
# The two text effects this VDI really applies.  The font's METRICS are
# the device's now (devref.py), because a screen 320 pixels wide cannot
# spend eight of them on a character and still be a GEM.
TXT_THICKEN, TXT_UNDERLINE = 0x01, 0x08
TXT_DONE = TXT_THICKEN | TXT_UNDERLINE
TA_LEFT, TA_CENTRE, TA_RIGHT = 0, 1, 2
TA_BASE, TA_HALF, TA_ASCENT, TA_BOTTOM, TA_DESCENT, TA_TOP = range(6)
FONT_ID_SYS, FONT_SYSTEM, FONT_LOADED = 1, 1, 2
FONT_SYSNAME = "gem4xe system 8x8"    # what vqt_name(1) answers
V_PMARKER, V_FILLAREA, V_GDP, VST_ROTATION = 7, 9, 11, 13
VSM_TYPE, VSM_HEIGHT, VSM_COLOR = 18, 19, 20
VQL_ATTRIBUTES, VQM_ATTRIBUTES, VQF_ATTRIBUTES = 35, 36, 37
V_CONTOURFILL, VSF_PERIMETER, V_GET_PIXEL, VSL_ENDS = 103, 104, 105, 108
LE_SQUARED, LE_ARROWED, LE_ROUNDED = 0, 1, 2
# markers (src/vdi/vdi.h): the nominal cell is the ST's
MIN_MARK_STYLE, MAX_MARK_STYLE, DEF_MARK_STYLE = 1, 6, 3
DEF_MKWD, DEF_MKHT, MAX_MKWD, MAX_MKHT = 15, 11, 120, 88
# The six marker shapes, in the donor's encoding: a count of polylines, then
# for each a count of points and that many x,y offsets from the centre.
MARKERS = (
    (1, 2, 0, 0, 0, 0),                                     # dot
    (2, 2, 0, -3, 0, 3, 2, -4, 0, 4, 0),                    # plus
    (3, 2, 0, -3, 0, 3, 2, 3, 2, -3, -2, 2, 3, -2, -3, 2),  # star
    (1, 5, -4, -3, 4, -3, 4, 3, -4, 3, -4, -3),             # square
    (2, 2, -4, -3, 4, 3, 2, -4, 3, 4, -3),                  # cross
    (1, 5, -4, 0, 0, -3, 4, 0, 0, 3, -4, 0),                # diamond
)
# The GDPs (v_gdp's contrl[5])
GDP_BAR, GDP_ARC, GDP_PIE, GDP_CIRCLE, GDP_ELLIPSE = 1, 2, 3, 4, 5
GDP_ELLARC, GDP_ELLPIE, GDP_RBOX, GDP_RFBOX, GDP_JUSTIFIED = 6, 7, 8, 9, 10
HALFPI, GDP_PI, TWOPI = 900, 1800, 3600
VDI_SIN_ANGLE_MAX = 896
MIN_ARC_CT, MAX_ARC_CT = 16, 48
CORNER_POINTS = 5
Isin225, Isin450, Isin675 = 12539, 23170, 30273
Icos225, Icos450, Icos675 = Isin675, Isin450, Isin225

# clc_flit's edge buffer, and the room ptsin leaves to close a polygon
# (src/vdi/vdi.h: PTSIN_SIZE / 2 - 1), and the size of intin
MAX_INTERSECT = 32
MAX_POLY = 63
INTIN_SIZE = 128

V_LOCATOR = 28
V_STRING, VQ_KEY_S = 31, 128
VSF_UDPAT = 112
MD_REPLACE, MD_TRANS, MD_XOR, MD_ERASE = 1, 2, 3, 4

LINE_STYLES = [0xFFFF, 0xFFFF, 0xFFF0, 0xE0E0, 0xFF18, 0xFF00, 0xF191]  # 7: ud_ls
# The physical workstation's handle, by specification, and how many the
# driver has, virtual ones included (vdi.c NUM_VWK).
VDI_PHYS_HANDLE = 1
NUM_VWK = 4

# The font strips live in tools/fontref.py, below both this model and the
# two surface models: a face is the DEVICE's (devref.py), and putting the
# loader here made the import graph a cycle.  The names stay -- FONT is
# the 8x8 the VBXE device carries, FONT_STRIDE the strip's layout, which
# is the same for every face.
FONT_STRIDE = fontref.FONT_STRIDE
FONT = fontref.FONT_8X8


# The VDI's sine table, read from the file the target links (generated by
# tools/sinconv.py from EmuTOS): sines of 0 to 89.6 degrees in 0.8 degree
# steps, normalised to 0..65536.
_SIN_C = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "src", "vdi", "sintbl.c")


def _load_sin():
    text = open(_SIN_C).read()
    body = text[text.index("{"):]
    vals = [int(v) for v in re.findall(r"\d+", body)]
    if len(vals) != (VDI_SIN_ANGLE_MAX // 8) + 1:
        raise RuntimeError(f"{_SIN_C}: {len(vals)} entries")
    return vals


SIN_TBL = _load_sin()

# The fill patterns, likewise read from the generated file the target links
# (tools/patconv.py from EmuTOS's vdi_fill.c).  tests/host/test_fillpat.py
# holds that file to the donor.  Interior styles, as vsf_interior takes them:
FIS_HOLLOW, FIS_SOLID, FIS_PATTERN, FIS_HATCH, FIS_USER = 0, 1, 2, 3, 4
MAX_FILL_PATTERN, MAX_FILL_HATCH = 24, 12
# The work_in the AES opens the screen with: every attribute 1 -- line style
# 1, colours 1 (black), SOLID fill, index 1 -- and raster coordinates.  A
# workstation opened without a work_in gets this one.
WORK_IN = (1,) * 10 + (2,)
_PAT_C = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "src", "vdi", "fillpat.c")


def _load_patterns():
    text = open(_PAT_C).read()
    out = {}
    # FAR since the tables moved to `cfar`: bank $00 had no room for
    # 608 bytes of them (docs/phase24.md).
    for m in re.finditer(r"const UWORD (?:FAR )?(\w+)\[(\d+)\]\s*=\s*\{(.*?)\};",
                         text, re.S):
        words = [int(w, 16) for w in re.findall(r"0x([0-9A-Fa-f]{4})", m.group(3))]
        if len(words) != int(m.group(2)):
            raise RuntimeError(f"{_PAT_C}: {m.group(1)} has {len(words)} words")
        out[m.group(1)] = words
    return out


_PAT = _load_patterns()
FILL_DITHER, FILL_OEM = _PAT["fill_dither"], _PAT["fill_oem"]
FILL_HATCH0, FILL_HATCH1 = _PAT["fill_hatch0"], _PAT["fill_hatch1"]

# GEM's standard palette order, from devref: what a DEVICE does with it
# -- permute it, reduce it to two luminances, ignore it -- is the
# device's business, so that is where it lives.  The VDI keeps only what
# was ASKED for, in pal_req, which vq_color answers from.
GEM_PAL = devref.GEM_PAL

# The VDI pen -> hardware pen permutation moved to the VBXE device with
# the rest of that screen's business (tools/devref.py, Vbxe.MAP_COL).


def col_to_hw(v):
    """The VDI's thousandths into the eight bits the palette takes
    (src/vdi/vdi.c, col_to_hw)."""
    v = 0 if v < 0 else 1000 if v > 1000 else v
    return (v * 255 + 500) // 1000


def hw_to_col(h):
    """And back, through the DAC: VBXE keeps seven significant bits and
    copies the top one into the eighth."""
    dac = (h & 0xFE) | ((h >> 7) & 1)
    return (dac * 1000 + 127) // 255



# The target's result record (src/m3_vdi.c): contrl[2], contrl[4], then
# RESULT_INTOUT words of intout and three of ptsout.  Fifteen intout words
# because evnt_multi returns seven values and an eight-word message.
RESULT_INTOUT = 15
RESULT_WORDS = 2 + RESULT_INTOUT + 3


def record(c2, c4, intout, ptsout):
    """The target's result record, (contrl[2], contrl[4], intout[0..14],
    ptsout[0..2]): only the declared words are non-zero."""
    io = tuple((intout[k] if k < len(intout) else 0) if c4 > k else 0
               for k in range(RESULT_INTOUT))
    po = (ptsout[0] if c2 > 0 else 0,
          ptsout[1] if c2 > 0 else 0,
          ptsout[2] if c2 > 1 else 0)
    return (c2, c4) + io + po


def decode(blob, n):
    """The n result records in a dump of the target's results area, as the
    tuples record() builds."""
    size = RESULT_WORDS * 2
    return [tuple(int.from_bytes(bytes(blob[i * size + k * 2:i * size + k * 2 + 2]),
                                 "little", signed=True)
                  for k in range(RESULT_WORDS))
            for i in range(n)]


class VDI:
    def __init__(self, dev=None):
        # THE DEVICE THIS VDI DRAWS ON (tools/devref.py; src/vdi/vdidev.h
        # on the other side).  Below the seam: the packing, the palette
        # order, the font's cell, where a form lives.  Above it -- every
        # line of this file -- none of that is named, which is what lets
        # the same rasteriser answer for a second screen.
        self.dev = devref.Vbxe() if dev is None else dev
        self.font = self.dev.face
        # The input vectors and the button edge detector are the driver's,
        # not the workstation's: v_opnwk does not reset them (vdi.c).
        self.vec_motv = self.vec_butv = self.vec_timv = None
        self.last_buttons = 0
        self.reset()
        self.dev.clear()                    # pen 0 = white

    # What a workstation carries (vdi.c Vwk): the attributes, the clip,
    # its user pattern and line style.  The driver keeps one set current
    # and swaps by handle; so does this.
    WK_FIELDS = ("clip", "xmn", "ymn", "xmx", "ymx", "wrt_mode", "line_width",
                 "line_index", "line_color", "text_color",
                 "fill_style", "fill_index", "fill_color", "fill_per",
                 "ud_patrn", "ud_ls", "h_align", "v_align", "text_effects",
                 "mark_index", "mark_color", "mark_height", "mark_scale",
                 "line_beg", "line_end")

    # The face in use, and the one a .FNT would load: a gate that puts a
    # font on the disk calls load_font() with the same file's bytes, so
    # the two sides draw from the same strip (src/vdi/font.c).
    font_file = None            # the loaded strip, or None
    font_name = ""
    font_id = FONT_ID_SYS

    def load_font(self, strip, name, font_id):
        """What the disk's SYSTEM.FNT holds.  The system loads it at
        start-up, so the model starts with it in use as well."""
        self.font_file, self.font_name, self.font_id = strip, name, font_id
        self.font = strip

    def reset(self):
        # v_opnwk: the physical workstation, handle 1, and every virtual
        # one closed with it
        self.handle = VDI_PHYS_HANDLE
        self.wk = {}                # the open workstations NOT current, by handle
        self._init_wk(WORK_IN)
        # mouse cursor
        # The palette, per workstation copy: vs_color changes it, and
        # vq_color answers both what was asked for and what the DAC made
        # of it (src/vdi/vdi.c, pal_req).
        self.dev.palette_all(GEM_PAL)
        self.pal_req = [[hw_to_col(GEM_PAL[p * 3 + k]) for k in range(3)]
                        for p in range(16)]
        self.cur_xhot = self.cur_yhot = 0
        self.cur_bg, self.cur_fg = 0, 1
        self.cur_mask = [0] * 16
        self.cur_data = [0] * 16
        self.cur_hide = 1          # visible only at 0; starts hidden
        self.cur_drawn = False
        self.cur_lastx = self.cur_lasty = -1
        self.dev.cursor_discard()  # what was under the pointer: the device's
        self.ptr_x, self.ptr_y = 0, 0
        self.buttons = 0
        # The keyboard: codes waiting to be read one per v_string, and the
        # modifier bits vq_key_s reports for the key held right now.
        self.keys = []
        self.key_mods = 0
        self.in_mode = [0, 2, 2, 2, 2]
        self.contrl2 = self.contrl4 = 0
        self.intout = [0, 0, 0]
        self.ptsout = [0, 0, 0]

    # -- geometry --------------------------------------------------------
    def _clip_rect(self, x1, y1, x2, y2):
        if self.clip:
            x1 = max(x1, self.xmn); y1 = max(y1, self.ymn)
            x2 = min(x2, self.xmx); y2 = min(y2, self.ymx)
        x1 = max(x1, 0); y1 = max(y1, 0)
        x2 = min(x2, self.dev.w - 1); y2 = min(y2, self.dev.h - 1)
        return (x1, y1, x2, y2) if (x1 <= x2 and y1 <= y2) else None

    def _visible(self, x, y):
        """Inside the WORKSTATION's clip.  The screen's own edge is the
        device's business and it checks it again."""
        if self.clip and not (self.xmn <= x <= self.xmx and
                              self.ymn <= y <= self.ymx):
            return False
        return 0 <= x < self.dev.w and 0 <= y < self.dev.h

    def _plot(self, x, y, pen):
        """One pixel in a VDI pen, clipped by the workstation."""
        if not self._visible(x, y):
            return
        self.dev.plot(x, y, pen)

    def _plot_xor(self, x, y):
        if not self._visible(x, y):
            return
        self.dev.plot_xor(x, y)

    def _init_wk(self, w):
        """init_wk: the attributes a workstation opens with, from work_in,
        validated as the setters validate them, the clip off and the rest
        at their defaults.  Donor names: fill_style is the INTERIOR
        (hollow/solid/pattern/hatch/user), fill_index is vsf_style's index
        minus one -- the minus one the ROM's init forgets, which gem4xe
        does not reproduce."""
        self.clip = 0
        self.h_align, self.v_align, self.text_effects = TA_LEFT, TA_BASE, 0
        self.xmn, self.ymn = 0, 0
        self.xmx, self.ymx = self.dev.w - 1, self.dev.h - 1
        self.wrt_mode = 0
        self.line_width = 1
        self.ud_patrn = [0] * 16
        self.ud_ls = 0xFFFF
        self.line_index = w[1] if 1 <= w[1] <= 7 else 1
        self.line_color = w[2] if 0 <= w[2] <= 15 else 1
        self.text_color = w[6] if 0 <= w[6] <= 15 else 1
        self.fill_style = w[7] if FIS_HOLLOW <= w[7] <= FIS_USER else FIS_HOLLOW
        top = MAX_FILL_PATTERN if self.fill_style == FIS_PATTERN else MAX_FILL_HATCH
        self.fill_index = (w[8] if 1 <= w[8] <= top else 1) - 1
        self.fill_color = w[9] if 0 <= w[9] <= 15 else 1
        self.fill_per = 1
        # work_in[3] and [4] are the marker: the type, and its colour
        self.mark_index = (w[3] if MIN_MARK_STYLE <= w[3] <= MAX_MARK_STYLE
                           else DEF_MARK_STYLE) - 1
        self.mark_color = w[4] if 0 <= w[4] <= 15 else 1
        self.mark_height, self.mark_scale = DEF_MKHT, 1
        self.line_beg = self.line_end = LE_SQUARED

    def _paint_pixel(self, x, y, pen, is_set):
        """One pixel of a primitive in the current writing mode, given
        whether the pattern bit is set there: replace = pen / pen 0,
        transparent = pen where set, XOR = complement where set, erase =
        pen where clear."""
        m = self.wrt_mode + 1
        if m == MD_TRANS:
            if is_set:
                self._plot(x, y, pen)
        elif m == MD_XOR:
            if is_set:
                self._plot_xor(x, y)
        elif m == MD_ERASE:
            if not is_set:
                self._plot(x, y, pen)
        else:
            self._plot(x, y, pen if is_set else 0)

    def _paint_rect(self, x1, y1, x2, y2, pen):
        """A solid rectangle in the current writing mode (already clipped)."""
        m = self.wrt_mode + 1
        if m == MD_XOR:
            self.dev.xor_rect(x1, y1, x2, y2)
        elif m == MD_ERASE:
            return
        else:
            self.dev.fill_rect(x1, y1, x2, y2, pen)

    def _fill_pattern(self):
        """st_fl_ptr: what the interior and index resolve to -- the rows of
        the current fill pattern and the mask that picks a row from y.  A
        hollow fill is a pattern of no bits, a solid one of all bits; the
        writing mode then says what a clear bit does (replace writes pen 0
        there, which is why a hollow box in replace mode is WHITE, not
        untouched)."""
        fs, fi = self.fill_style, self.fill_index
        if fs == FIS_SOLID:
            return [0xFFFF], 0
        if fs == FIS_PATTERN:
            if fi < 8:
                return FILL_DITHER[fi * 4:fi * 4 + 4], 3
            return FILL_OEM[(fi - 8) * 8:(fi - 8) * 8 + 8], 7
        if fs == FIS_HATCH:
            if fi < 6:
                return FILL_HATCH0[fi * 8:fi * 8 + 8], 7
            return FILL_HATCH1[(fi - 6) * 16:(fi - 6) * 16 + 16], 15
        if fs == FIS_USER:
            return list(self.ud_patrn), 15
        return [0x0000], 0

    def _patt_rect(self, x1, y1, x2, y2, pen):
        """A rectangle in the current fill pattern and writing mode (already
        clipped).  The pattern is anchored to the SCREEN, not the rectangle:
        row y uses pattern row (y & mask), bit 15 is pixel x = 0 mod 16."""
        rows, msk = self._fill_pattern()
        if all(r == 0xFFFF for r in rows):
            self._paint_rect(x1, y1, x2, y2, pen)
            return
        m = self.wrt_mode + 1
        if all(r == 0 for r in rows):
            if m == MD_REPLACE:
                self.dev.fill_rect(x1, y1, x2, y2, 0)
            elif m == MD_ERASE:
                self.dev.fill_rect(x1, y1, x2, y2, pen)
            return
        for y in range(y1, y2 + 1):
            r = rows[y & msk]
            for x in range(x1, x2 + 1):
                self._paint_pixel(x, y, pen, (r >> (15 - (x & 15))) & 1)

    def _line(self, x1, y1, x2, y2):
        mask = (self.ud_ls if self.line_index == 7
                else LINE_STYLES[self.line_index if 1 <= self.line_index <= 6 else 1])
        if y1 == y2 and mask == 0xFFFF:
            a, b = sorted((x1, x2))
            r = self._clip_rect(a, y1, b, y2)
            if r:
                self._paint_rect(*r, self.line_color)
            return
        if x1 == x2 and mask == 0xFFFF:
            a, b = sorted((y1, y2))
            r = self._clip_rect(x1, a, x2, b)
            if r:
                self._paint_rect(*r, self.line_color)
            return
        dx, dy = abs(x2 - x1), abs(y2 - y1)
        sx = 1 if x1 < x2 else -1
        sy = 1 if y1 < y2 else -1
        err, bit = dx - dy, 0
        while True:
            self._paint_pixel(x1, y1, self.line_color,
                              mask & (1 << (15 - (bit & 15))))
            bit += 1
            if x1 == x2 and y1 == y2:
                break
            e2 = err << 1
            if e2 > -dy:
                err -= dy; x1 += sx
            if e2 < dx:
                err += dx; y1 += sy

    def _rform(self, f):
        """(base, stride, w, h, is_screen) of a raster form: None is the
        screen, otherwise a VramForm (vdi.c rform_of)."""
        if f is None:
            return self.dev.screen_form()
        return f.addr, f.stride, f.w, f.h, False

    @staticmethod
    def _clip_to(x1, y1, x2, y2, w, h):
        x1 = max(x1, 0); y1 = max(y1, 0)
        x2 = min(x2, w - 1); y2 = min(y2, h - 1)
        return (x1, y1, x2, y2) if (x1 <= x2 and y1 <= y2) else None

    def _cpyfm(self, pts, src=None, dst=None):
        """Mirrors vdi_vro_cpyfm(), including the alignment fast/slow split.

        The VBXE blitter has no shifter, so 4bpp pixels can only be moved
        between positions of the same parity.  Both paths must produce the
        same pixels -- that is what the conformance cases check.

        src and dst are the forms: None for the screen, a VramForm for the
        AES's save buffer.  The destination is clipped to the workstation's
        rectangle and the screen when it IS the screen and to its own bounds
        otherwise; the source is clipped to its form's bounds, each clip
        dropping the same span from the other end -- the driver's rule, not
        the donor's, which never clips a source.
        """
        sx1, sx2 = sorted((pts[0], pts[2]))
        sy1, sy2 = sorted((pts[1], pts[3]))
        dx1, dx2 = sorted((pts[4], pts[6]))
        dy1, dy2 = sorted((pts[5], pts[7]))
        w, h = sx2 - sx1 + 1, sy2 - sy1 + 1
        if w <= 0 or h <= 0:
            return
        sb, ss, sw, sh, _ = self._rform(src)
        db, ds, dw, dh, dscreen = self._rform(dst)
        if dscreen:
            c = self._clip_rect(dx1, dy1, dx1 + w - 1, dy1 + h - 1)
        else:
            c = self._clip_to(dx1, dy1, dx1 + w - 1, dy1 + h - 1, dw, dh)
        if c is None:
            return
        cx1, cy1, cx2, cy2 = c
        sx1 += cx1 - dx1
        sy1 += cy1 - dy1
        dx1, dy1 = cx1, cy1
        w, h = cx2 - cx1 + 1, cy2 - cy1 + 1
        sx2, sy2 = sx1 + w - 1, sy1 + h - 1
        c = self._clip_to(sx1, sy1, sx2, sy2, sw, sh)
        if c is None:
            return
        cx1, cy1, cx2, cy2 = c
        dx1 += cx1 - sx1
        dy1 += cy1 - sy1
        sx1, sy1 = cx1, cy1
        w, h = cx2 - cx1 + 1, cy2 - cy1 + 1
        self.dev.copy(sb, ss, sx1, sy1, db, ds, dx1, dy1, w, h)

    def _vrt_cpyfm(self, pts, ints, form):
        """Mirrors vdi_vrt_cpyfm(): a 1-plane source expanded into colours.

        `form` is (bits, wdwidth) -- the same bytes the harness poked into the
        target's scratch area, MSB-first, rows fd_wdwidth WORDS apart.
        """
        bits, wdwidth = form
        mode = ints[0]
        fg, bg = ints[1] & 15, ints[2] & 15
        sx1, sx2 = sorted((pts[0], pts[2]))
        sy1, sy2 = sorted((pts[1], pts[3]))
        dx1, dy1 = pts[4], pts[5]
        w, h = sx2 - sx1 + 1, sy2 - sy1 + 1
        if w <= 0 or h <= 0:
            return
        stride = wdwidth * 2
        for row in range(h):
            base = (sy1 + row) * stride
            for col in range(w):
                sx = sx1 + col
                on = (bits[base + (sx >> 3)] >> (7 - (sx & 7))) & 1
                dx, dy = dx1 + col, dy1 + row
                if mode == MD_TRANS:
                    if on:
                        self._plot(dx, dy, fg)
                elif mode == MD_XOR:
                    if on:
                        self._plot_xor(dx, dy)
                elif mode == MD_ERASE:
                    if not on:
                        self._plot(dx, dy, bg)
                else:
                    self._plot(dx, dy, fg if on else bg)

    def _align_x(self, x, w):
        """Where the point a string is given puts its first cell, given
        what vst_alignment set and how WIDE the string will be
        (src/vdi/vdi.c, align_x)."""
        if self.h_align == TA_CENTRE:
            return x - w // 2
        if self.h_align == TA_RIGHT:
            return x - w
        return x

    def _align_y(self, y):
        d = self.dev
        return {TA_HALF: y - d.font_half, TA_ASCENT: y - d.font_ascent,
                TA_BOTTOM: y - d.font_h + 1,
                TA_DESCENT: y - d.font_top - d.font_descent,
                TA_TOP: y}.get(self.v_align, y - d.font_top)

    def _glyph(self, code, cx, cy):
        for row in range(self.dev.font_h):
            b = self.font[row * FONT_STRIDE + (code & 0xFF)]
            for col in range(self.dev.font_w):
                self._paint_pixel(cx + col, cy + row, self.text_color,
                                  b & (0x80 >> col))

    def _draw_char(self, code, cx, cy):
        """One glyph at a cell's top-left corner, thickened if
        vst_effects asked for it (src/vdi/vdi.c, draw_char).  Each pixel
        goes through the writing-mode rules of _paint_pixel."""
        self._glyph(code, cx, cy)
        if (self.text_effects & TXT_THICKEN
                and cx + 1 + self.dev.font_w <= self.dev.w):
            self._glyph(code, cx + 1, cy)

    def _underline(self, x1, x2, cy):
        """The row under a string: SOLID and clipped, in the text colour,
        because an underline is text and takes no fill pattern."""
        b = cy + self.dev.font_h - 1
        r = self._clip_rect(x1, b, x2, b)
        if r:
            self._paint_rect(*r, self.text_color)

    def _gtext(self, pts, ints):
        """Mirrors vdi_v_gtext().  The point given is placed by
        vst_alignment -- left and the BASELINE by default, the cell top
        then being y - the font's top."""
        n = len(ints)
        fw = self.dev.font_w
        x = self._align_x(pts[0], n * fw)
        cy = self._align_y(pts[1])
        for i, code in enumerate(ints):
            self._draw_char(code, x + i * fw, cy)
        if self.text_effects & TXT_UNDERLINE and n:
            w = n * fw + (1 if self.text_effects & TXT_THICKEN else 0)
            self._underline(x, x + w - 1, cy)

    # -- filled areas ----------------------------------------------------

    def _polyline_pts(self, pt, n):
        """v_pline's loop over an array the caller names."""
        for i in range(n - 1):
            self._line(pt[i * 2], pt[i * 2 + 1], pt[i * 2 + 2], pt[i * 2 + 3])

    def _fill_perimeter(self, pt, n):
        """SOLID and in the FILL colour, whatever the line attributes say
        (src/vdi/vdi.c, fill_perimeter)."""
        sv_color, sv_index = self.line_color, self.line_index
        self.line_color, self.line_index = self.fill_color, 1
        self._polyline_pts(pt, n)
        self.line_color, self.line_index = sv_color, sv_index

    def _recfl(self, pts):
        """vr_recfl, and what a GDP bar is made of."""
        x1, x2 = sorted((pts[0], pts[2]))
        y1, y2 = sorted((pts[1], pts[3]))
        r = self._clip_rect(x1, y1, x2, y2)
        if r:
            self._patt_rect(*r, self.fill_color)

    def _fill_span(self, x1, x2, y):
        """One scan line of an interior: the clip rectangle, then the
        screen."""
        if self.clip:
            if x1 < self.xmn:
                if x2 < self.xmn:
                    return
                x1 = self.xmn
            if x2 > self.xmx:
                if x1 > self.xmx:
                    return
                x2 = self.xmx
        if x2 < 0 or x1 > self.dev.w - 1:
            return
        x1, x2 = max(x1, 0), min(x2, self.dev.w - 1)
        self._patt_rect(x1, y, x2, y, self.fill_color)

    @staticmethod
    def _mul_div(a, b, d):
        """(a*b)/d truncated TOWARD ZERO, as the 68000's divs and C both
        do it -- Python's // floors, which differs on negatives."""
        q = abs(a * b) // abs(d)
        return q if (a * b < 0) == (d < 0) else -q

    def _clc_flit(self, pt, vectors, start, end):
        """For each scan line, where every edge crosses it, sorted, filled
        in pairs.  `end` is one ABOVE the topmost line and the loop stops
        before it, so a polygon does not paint its own top row -- the
        donor's rule (src/vdi/vdi.c, clc_flit)."""
        for y in range(start, end, -1):
            xs = []
            for i in range(vectors):
                y1, y2 = pt[i * 2 + 1], pt[i * 2 + 3]
                dy = y2 - y1
                if not dy:
                    continue
                dy1, dy2 = y - y1, y - y2
                if (dy1 ^ dy2) >= 0:
                    continue
                if len(xs) >= MAX_INTERSECT:
                    break
                x1, x2 = pt[i * 2], pt[i * 2 + 2]
                dx = (x2 - x1) * 2
                if dx < 0:
                    xs.append(((self._mul_div(dy2, dx, dy) + 1) >> 1) + x2)
                else:
                    xs.append(((self._mul_div(dy1, dx, dy) + 1) >> 1) + x1)
            if len(xs) < 2:
                continue
            xs.sort()
            for i in range(0, len(xs) - 1, 2):
                self._fill_span(xs[i], xs[i + 1], y)

    def _polygon(self, pt, n):
        """The interior, then the perimeter if vsf_perimeter asked for one.
        pt is closed here, as the driver closes it in ptsin."""
        if n < 2:
            return
        ys = [pt[i * 2 + 1] for i in range(n)]
        miny, maxy = min(ys), max(ys)
        if self.clip:
            if maxy < self.ymn or miny > self.ymx:
                return
            miny = max(miny, self.ymn - 1)
            maxy = min(maxy, self.ymx)
        if maxy < 0 or miny > self.dev.h - 1:
            return
        miny, maxy = max(miny, -1), min(maxy, self.dev.h - 1)
        pt = list(pt[:n * 2]) + [pt[0], pt[1]]
        self._clc_flit(pt, n, maxy, miny)
        if self.fill_per:
            self._fill_perimeter(pt, n + 1)

    def _pmarker(self, pts):
        """Each point gets the current marker, drawn as the polylines that
        define it -- solid, in the marker colour, at the marker scale.  The
        donor also turns clipping on for good here; gem4xe does not."""
        sv_index, sv_color = self.line_index, self.line_color
        self.line_index, self.line_color = 1, self.mark_color
        for i in range(len(pts) // 2):
            cx, cy = pts[i * 2], pts[i * 2 + 1]
            m = MARKERS[self.mark_index]
            k = 1
            for _ in range(m[0]):
                n = m[k]; k += 1
                seg = []
                for _ in range(min(n, 5)):
                    seg.append(cx + self.mark_scale * m[k])
                    seg.append(cy + self.mark_scale * m[k + 1])
                    k += 2
                self._polyline_pts(seg, n)
        self.line_index, self.line_color = sv_index, sv_color

    # -- v_contourfill, and the arrowheads vsl_ends asks for -------------

    def _cf_pixel(self, x, y):
        """What the device stores at (x, y).  The paint bucket compares
        DEVICE values, not pens: it is looking for a boundary on the
        screen, and only the device knows what one looks like."""
        return self.dev.pixel(x, y)

    def _contourfill(self, pts, ints):
        """The paint bucket.  The region is found first and painted after,
        so the answer does not depend on the order of the walk -- which is
        why the driver may use a stack in far memory and this a list
        (src/vdi/vdi.c, vdi_v_contourfill)."""
        x, y = pts[0], pts[1]
        index = ints[0] if ints else -1
        x0, y0, x1, y1 = 0, 0, self.dev.w - 1, self.dev.h - 1
        if self.clip:
            x0, y0 = max(x0, self.xmn), max(y0, self.ymn)
            x1, y1 = min(x1, self.xmx), min(y1, self.ymx)
        if not (x0 <= x <= x1 and y0 <= y <= y1):
            return
        if index >= 0:
            search, typ = self.dev.pen_value(index & 15), 0
        else:
            search, typ = self._cf_pixel(x, y), 1

        def inside(px, py):
            if not (x0 <= px <= x1 and y0 <= py <= y1):
                return False
            hw = self._cf_pixel(px, py)
            return (hw == search) if typ else (hw != search)

        seen = set()
        stack = [(x, y)]
        while stack:
            sx, sy = stack.pop()
            if (sx, sy) in seen or not inside(sx, sy):
                continue
            a = sx
            while a > x0 and inside(a - 1, sy):
                a -= 1
            b = sx
            while b < x1 and inside(b + 1, sy):
                b += 1
            for i in range(a, b + 1):
                seen.add((i, sy))
            for yy in (sy - 1, sy + 1):
                i = a
                while i <= b:
                    if inside(i, yy) and (i, yy) not in seen:
                        stack.append((i, yy))
                        while i <= b and inside(i, yy):
                            i += 1
                    i += 1
        # painted row by row, run by run, through the fill pattern
        for yy in range(y0, y1 + 1):
            xx = x0
            while xx <= x1:
                if (xx, yy) not in seen:
                    xx += 1
                    continue
                a = xx
                while xx <= x1 and (xx, yy) in seen:
                    xx += 1
                self._patt_rect(a, yy, xx - 1, yy, self.fill_color)

    @staticmethod
    def _mul_div_round(m1, m2, d):
        v = m1 * m2
        v = v - d // 2 if v < 0 else v + d // 2
        return VDI._trunc(v, d)

    def _draw_arrow(self, pt, base, count, inc):
        """One arrowhead at the point pt[base], pointing away from the
        first point far enough back to carry it.  A filled triangle in the
        LINE colour, and the end point is pulled back to its base
        afterwards (src/vdi/vdi.c, draw_arrow)."""
        alen, awid = 8, 4
        dx = dy = 0
        nskip = 0
        len2 = 0
        for i in range(1, count):
            nskip = i
            dx = pt[base] - pt[base + i * inc * 2]
            dy = pt[base + 1] - pt[base + i * inc * 2 + 1]
            len2 = dx * dx + dy * dy
            if len2 >= alen * alen:
                break
        line_len = math.isqrt(len2)
        if line_len < alen:
            return
        dxf = self._mul_div_round(dx, 1000, line_len)
        dyf = self._mul_div_round(dy, 1000, line_len)
        htx = self._mul_div_round(alen, dxf, 1000)
        hty = self._mul_div_round(alen, dyf, 1000)
        bx = self._mul_div_round(awid, -dyf, 1000)
        by = self._mul_div_round(awid, dxf, 1000)
        tri = [pt[base] + bx - htx, pt[base + 1] + by - hty,
               pt[base] - bx - htx, pt[base + 1] - by - hty,
               pt[base], pt[base + 1]]
        sv = (self.fill_style, self.fill_index, self.fill_color, self.fill_per)
        self.fill_style, self.fill_color, self.fill_per = FIS_SOLID, self.line_color, 0
        self._polygon(tri, 3)
        (self.fill_style, self.fill_index,
         self.fill_color, self.fill_per) = sv
        # the tip comes back to the head's base, and the points the head
        # swallowed come with it -- those BETWEEN the tip and the point
        # the direction came from, which for a two-point line is none
        pt[base] -= htx
        pt[base + 1] -= hty
        for k in range(nskip - 1, 0, -1):
            pt[base + k * inc * 2] = pt[base]
            pt[base + k * inc * 2 + 1] = pt[base + 1]

    def _line_ends(self, pt, n):
        if n < 2:
            return
        if self.line_beg == LE_ARROWED:
            self._draw_arrow(pt, 0, n, 1)
        if self.line_end == LE_ARROWED:
            self._draw_arrow(pt, (n - 1) * 2, n, -1)

    # -- the graphics device primitives (v_gdp) --------------------------
    # Angles are in tenths of a degree, anticlockwise from east.

    @staticmethod
    def _Isin(angle):
        i, rem = angle >> 3, angle & 7
        v = SIN_TBL[i]
        if rem:
            v += (((SIN_TBL[i + 1] - v) & 0xFFFF) * rem) >> 3
        return v & 0xFFFF

    @classmethod
    def _Icos(cls, angle):
        return cls._Isin(HALFPI - angle)

    @staticmethod
    def _umul_shift(a, b):
        return ((a * b) + 32768) >> 16

    def _clc_pts(self, angle, xc, yc, xrad, yrad):
        """Where an angle lands on the ellipse, in raster coordinates: y
        grows downward, so the first quadrant's y offset is negative."""
        neg_x, neg_y = False, True
        while angle >= TWOPI:
            angle -= TWOPI
        if angle > 3 * HALFPI:              # fourth quadrant
            angle, neg_x, neg_y = TWOPI - angle, False, False
        elif angle > GDP_PI:                # third
            angle, neg_x, neg_y = angle - GDP_PI, True, False
        elif angle > HALFPI:                # second
            angle, neg_x, neg_y = GDP_PI - angle, True, True
        if angle > VDI_SIN_ANGLE_MAX:
            xdiff, ydiff = 0, yrad
        elif angle < HALFPI - VDI_SIN_ANGLE_MAX:
            xdiff, ydiff = xrad, 0
        else:
            xdiff = self._umul_shift(self._Icos(angle), xrad & 0xFFFF)
            ydiff = self._umul_shift(self._Isin(angle), yrad & 0xFFFF)
        if neg_x:
            xdiff = -xdiff
        if neg_y:
            ydiff = -ydiff
        return [xc + xdiff, yc + ydiff]

    @staticmethod
    def _clc_nsteps(xrad, yrad):
        steps = max(xrad, yrad) >> 2
        return min(max(steps, MIN_ARC_CT), MAX_ARC_CT)

    def _clc_arc(self, sub, steps, xc, yc, xrad, yrad, beg, del_ang, end):
        pt = self._clc_pts(beg, xc, yc, xrad, yrad)
        for i in range(1, steps):
            angle = self._mul_div(del_ang, i, steps) + beg
            p = self._clc_pts(angle, xc, yc, xrad, yrad)
            if p != pt[-2:]:                # duplicates ignored
                pt += p
        pt += self._clc_pts(end, xc, yc, xrad, yrad)
        if sub in (GDP_PIE, GDP_ELLPIE):
            pt += [xc, yc]                  # a wedge closes on the centre
        n = len(pt) // 2
        if sub in (GDP_ARC, GDP_ELLARC):
            self._polyline_pts(pt, n)
        else:
            self._polygon(pt, n)

    def _gdp_curve(self, sub, pts, ints):
        xc, yc = pts[0], pts[1]
        if sub <= GDP_CIRCLE:
            xrad = yrad = pts[4] if sub == GDP_CIRCLE else pts[6]
        else:
            xrad, yrad = pts[2], pts[3]
        xrad, yrad = abs(xrad), abs(yrad)
        if self.clip and (xc + xrad < self.xmn or xc - xrad > self.xmx or
                          yc + yrad < self.ymn or yc - yrad > self.ymx):
            return
        if sub in (GDP_CIRCLE, GDP_ELLIPSE):
            beg, end = 0, TWOPI
        else:
            beg, end = ints[0], ints[1]
        d = end - beg
        if d < 0:
            d += TWOPI
        self._clc_arc(sub, self._clc_nsteps(xrad, yrad),
                      xc, yc, xrad, yrad, beg, d, end)

    def _gdp_rbox(self, sub, pts):
        x1, y1, x2, y2 = pts[0], pts[1], pts[2], pts[3]
        if x1 > x2:
            x1, x2 = x2, x1
        if y1 < y2:
            y1, y2 = y2, y1                 # (x1,y1) is the lower left
        # a sixty-fourth of the screen, clamped to half the shorter side
        xr = min(self.dev.w >> 6, (x2 - x1) // 2)
        yr = min(xr, (y1 - y2) // 2)        # square pixels: the same radius
        xoff = [0,
                self._mul_div(Icos675, xr, 32767),
                self._mul_div(Icos450, xr, 32767),
                self._mul_div(Icos225, xr, 32767),
                xr]
        yoff = [yr,
                self._mul_div(Isin675, yr, 32767),
                self._mul_div(Isin450, yr, 32767),
                self._mul_div(Isin225, yr, 32767),
                0]
        pt = []
        xc, yc = x2 - xr, y2 + yr                       # upper right
        for i in range(CORNER_POINTS):
            pt += [xc + xoff[i], yc - yoff[i]]
        yc = y1 - yr                                    # lower right
        for i in range(CORNER_POINTS - 1, -1, -1):
            pt += [xc + xoff[i], yc + yoff[i]]
        xc = x1 + xr                                    # lower left
        for i in range(CORNER_POINTS):
            pt += [xc - xoff[i], yc + yoff[i]]
        yc = y2 + yr                                    # upper left
        for i in range(CORNER_POINTS - 1, -1, -1):
            pt += [xc - xoff[i], yc - yoff[i]]
        if sub == GDP_RBOX:
            pt += [pt[0], pt[1]]
            self._polyline_pts(pt, 4 * CORNER_POINTS + 1)
        else:
            self._polygon(pt, 4 * CORNER_POINTS)

    def _gdp_justified(self, pts, ints):
        """The string spread to a given width: the whole-pixel share goes
        to every gap, the remainder one pixel at a time to the first few."""
        cnt = len(ints) - 2
        if cnt < 0:
            return
        interword, interchar, str_ = ints[0], ints[1], ints[2:]
        max_x = pts[2]
        spaces = sum(1 for c in str_ if c == ord(" ")) if interword else 0
        fw = self.dev.font_w
        width = cnt * fw
        wordx = rmword = rmwordx = 0
        charx = rmchar = rmcharx = 0
        if interword and spaces:
            delword = self._trunc(max_x - width, spaces)
            rmword = (max_x - width) - delword * spaces
            if rmword < 0:
                rmwordx, rmword = -1, -rmword
            else:
                rmwordx = 1
            if interchar:
                expand = fw // 2
                if delword > expand:
                    delword, rmword = expand, 0
                if delword < -expand:
                    delword, rmword = -expand, 0
                width += delword * spaces + rmword * rmwordx
            wordx = delword
        if interchar and cnt > 1:
            charx = self._trunc(max_x - width, cnt - 1)
            rmchar = (max_x - width) - charx * (cnt - 1)
            if rmchar < 0:
                rmcharx, rmchar = -1, -rmchar
            else:
                rmcharx = 1
        x = self._align_x(pts[0], max_x)
        cy = self._align_y(pts[1])
        x0, last = x, 0
        for c in str_:
            self._draw_char(c, x, cy)
            last = x
            x += fw + charx
            if rmchar:
                x += rmcharx
                rmchar -= 1
            if c == ord(" "):
                x += wordx
                if rmword:
                    x += rmwordx
                    rmword -= 1
        if self.text_effects & TXT_UNDERLINE and cnt > 0:
            self._underline(x0, last + fw - 1
                            + (1 if self.text_effects & TXT_THICKEN else 0), cy)

    @staticmethod
    def _trunc(a, b):
        """a / b truncated toward zero, as C divides."""
        q = abs(a) // abs(b)
        return q if (a < 0) == (b < 0) else -q

    def _v_gdp(self, sub, pts, ints):
        if sub == GDP_BAR:
            self._recfl(pts)
            if self.fill_per:
                xy = list(pts[:4]) + [0] * 6
                xy[5] = xy[7] = xy[3]
                xy[3] = xy[9] = xy[1]
                xy[4] = xy[2]
                xy[6] = xy[8] = xy[0]
                self._fill_perimeter(xy, 5)
        elif GDP_ARC <= sub <= GDP_ELLPIE:
            self._gdp_curve(sub, pts, ints)
        elif sub in (GDP_RBOX, GDP_RFBOX):
            self._gdp_rbox(sub, pts)
        elif sub == GDP_JUSTIFIED:
            self._gdp_justified(pts, ints)

    def _cell(self):
        """What vst_height, vqt_attributes and vst_point all answer:
        char width, char HEIGHT (the font's top, baseline to top of cell,
        as the ST ROM and EmuTOS both return it), cell width, cell
        height."""
        d = self.dev
        return [d.font_w, d.font_top, d.font_w, d.font_h]

    def _workout(self):
        """v_opnwk's work_out, in full: the per-call record carries only the
        first three words of each, but the AES reads further in (pixel size
        at intout[3..4], the character cell at ptsout[0..3]) and derives its
        layout from them.  Must match fill_workout() in src/vdi/vdi.c."""
        self.intout = [0] * 45
        self.ptsout = [0] * 12
        self.intout[0:15] = [self.dev.w - 1, self.dev.h - 1, 0,
                             372, 372,          # pixel width/height, microns
                             1, 7, 1, 6, 8, 1,  # char heights, line types,
                                                # widths, marker types/sizes,
                                                # faces
                             24, 12,            # patterns, hatches
                             self.dev.colours(), 10]
        # the ten GDPs, then the attribute each draws with (3 fill area,
        # 2 text, 0 polyline)
        self.intout[15:25] = list(range(1, 11))
        self.intout[25:35] = [3, 0, 3, 3, 3, 0, 3, 0, 3, 2]
        self.intout[35:43] = [1, 0, 1, 0, 16, 1, 1, 1]
        self.ptsout[0:4] = [self.dev.font_w, self.dev.font_h,
                            self.dev.font_w, self.dev.font_h]
        self.ptsout[4:8] = [1, 0, 1, 0]         # line width range
        self.ptsout[8:12] = [DEF_MKWD, DEF_MKHT, MAX_MKWD, MAX_MKHT]
        self.contrl2, self.contrl4 = 6, 45

    def _extnd1(self):
        """vq_extnd(1): the second capability block.  intout[4] = planes is
        the one the AES reads (gsx_start), intout[1] = 16 the one the
        harness records."""
        self.intout = [0] * 45
        self.ptsout = [0] * 12
        self.intout[0:7] = [0, self.dev.colours(), TXT_DONE, 0,
                            self.dev.planes(), 1, 1]
        self.intout[9:12] = [4, 2, 1]           # writing modes, input, align
        self.intout[14:17] = [MAX_POLY, INTIN_SIZE, 2]
        self.intout[19] = self.clip
        self.contrl2, self.contrl4 = 6, 45

    # -- cursor ----------------------------------------------------------
    # The VDI owns WHERE the pointer is, the hot spot, and the nesting
    # v_show_c and v_hide_c keep.  What was UNDER it is the device's:
    # nine bytes at odd x on one screen and five on the other, and
    # neither number belongs here.
    def _cursor_paint(self, cx, cy):
        """Data over mask over the screen.  Like real GEM's, the pointer
        ignores vs_clip: it is drawn wherever it is on the screen.  (Both
        this model and the target once clipped it -- agreeing, and wrong.)"""
        for row in range(16):
            m, d = self.cur_mask[row], self.cur_data[row]
            for col in range(16):
                bit = 0x8000 >> col
                if m & bit:
                    self.dev.plot(cx + col, cy + row, self.cur_bg & 15)
                if d & bit:
                    self.dev.plot(cx + col, cy + row, self.cur_fg & 15)

    def _cursor_show_now(self):
        cx, cy = self.ptr_x - self.cur_xhot, self.ptr_y - self.cur_yhot
        self.dev.cursor_save(cx, cy)
        self._cursor_paint(cx, cy)
        self.cur_drawn = True

    def _cursor_hide_now(self):
        if self.cur_drawn:
            self.dev.cursor_restore()
            self.cur_drawn = False

    def _cursor_move(self):
        """vdi_cursor_move(): erase-move-redraw, only when the pointer
        moved and the cursor is shown."""
        if self.cur_hide:
            return
        if ((self.ptr_x, self.ptr_y) == (self.cur_lastx, self.cur_lasty)
                and self.cur_drawn):
            return
        self._cursor_hide_now()
        self.cur_lastx, self.cur_lasty = self.ptr_x, self.ptr_y
        self._cursor_show_now()

    # -- workstations ----------------------------------------------------
    def _attrs(self):
        return {f: getattr(self, f) for f in self.WK_FIELDS}

    def _select(self, handle):
        """Make handle's workstation the current one; False when it is
        not open.  The user pattern and line style travel with it."""
        if handle == self.handle:
            return True
        if handle not in self.wk:
            return False
        self.wk[self.handle] = self._attrs()
        for f, val in self.wk.pop(handle).items():
            setattr(self, f, val)
        self.handle = handle
        return True

    def _opnvwk(self, ints):
        """v_opnvwk: the first free handle above the physical one, made
        current, with the attributes work_in asks for.  The driver answers
        handle 0 and does nothing else when its slots are all open; here
        that is an error, since no script means to.  The device --
        palette, pointer, screen -- is the physical workstation's and is
        not touched."""
        free = [h for h in range(VDI_PHYS_HANDLE + 1, NUM_VWK + 1)
                if h != self.handle and h not in self.wk]
        if not free:
            raise RuntimeError(f"v_opnvwk: the driver's {NUM_VWK} workstations "
                               f"are all open")
        self.wk[self.handle] = self._attrs()
        self.handle = free[0]
        self._init_wk(ints if len(ints) >= 11 else WORK_IN)
        self._workout()

    def _clsvwk(self):
        """v_clsvwk: the current workstation (the one the call named)
        unless it is the physical one; the physical one is current after."""
        if self.handle == VDI_PHYS_HANDLE:
            return
        for f, val in self.wk.pop(VDI_PHYS_HANDLE).items():
            setattr(self, f, val)
        self.handle = VDI_PHYS_HANDLE

    def close_virtuals(self):
        """What a program left open when it ended (vdi_close_virtuals)."""
        self._select(VDI_PHYS_HANDLE)
        self.wk = {}

    # -- dispatch --------------------------------------------------------
    def call(self, op, pts=(), ints=(), form=None, handle=None, sub=0):
        """One VDI call on workstation `handle` -- contrl[6] -- or on the
        current one when none is named: the physical one, unless the
        caller's script opened a virtual one, which is what an
        application's replayed calls do (m11, m16) and the runner's never
        do (src/m3_vdi.c names the physical one).  The AES names its own
        (aesref.vcall).  A handle that is not open gets nothing done and
        nothing back, as in the driver."""
        pts = list(pts); ints = list(ints)
        # Per-call outputs, mirroring what src/m3_vdi.c records: this is how
        # the input and inquiry opcodes get tested at all.
        self.contrl2 = 0
        self.contrl4 = 0
        self.intout = [0, 0, 0]
        self.ptsout = [0, 0, 0]
        if op not in (V_OPNWK, V_OPNVWK):
            if not self._select(self.handle if handle is None else handle):
                return
        if op == V_CLRWK:
            self.dev.clear()
        elif op == V_OPNWK:
            keep = (self.ptr_x, self.ptr_y)
            self.reset()
            self.ptr_x, self.ptr_y = keep
            if len(ints) >= 11:
                self._init_wk(ints)
            self._workout()
        elif op == V_OPNVWK:
            self._opnvwk(ints)
        elif op == V_CLSVWK:
            self._clsvwk()
        elif op == VQ_EXTND:
            if ints and ints[0]:
                self._extnd1()
            else:
                self._workout()
        elif op == VS_CLIP:
            self.clip = ints[0]
            if self.clip:
                x1, x2 = sorted((pts[0], pts[2]))
                y1, y2 = sorted((pts[1], pts[3]))
                self.xmn, self.ymn, self.xmx, self.ymx = x1, y1, x2, y2
            else:
                self.xmn, self.ymn = 0, 0
                self.xmx, self.ymx = self.dev.w - 1, self.dev.h - 1
        elif op == VR_RECFL:
            self._recfl(pts)
        elif op == VRO_CPYFM:
            if form:
                self._cpyfm(pts, form[0], form[1])
            else:
                self._cpyfm(pts)
        elif op == V_LOCATOR:
            if pts:
                self.ptr_x = max(0, min(pts[0], self.dev.w - 1))
                self.ptr_y = max(0, min(pts[1], self.dev.h - 1))
            self.ptsout[0], self.ptsout[1] = self.ptr_x, self.ptr_y
            self.intout[0] = 0
            self.contrl2, self.contrl4 = 1, 1
        elif op == VQ_MOUSE:
            self.intout[0] = self.buttons
            self.ptsout[0], self.ptsout[1] = self.ptr_x, self.ptr_y
            self.contrl2, self.contrl4 = 1, 1
        elif op == VSIN_MODE:
            dev, mode = ints[0], ints[1]
            if 1 <= dev <= 4 and mode in (1, 2):
                self.in_mode[dev] = mode
            self.intout[0] = 1
            self.contrl4 = 1
        elif op == VQIN_MODE:
            dev = ints[0]
            self.intout[0] = self.in_mode[dev] if 1 <= dev <= 4 else 2
            self.contrl4 = 1
        elif op == VST_HEIGHT:
            # char w, char h, cell w, cell h -- and "char height" is the
            # font's TOP (baseline to top of cell), as the ST ROM and EmuTOS
            # both return it; the AES adds it to a cell top for v_gtext.
            self.ptsout = self._cell()
            self.contrl2 = 2
        elif op == VQT_ATTRIBUTES:
            # font, colour, rotation, h/v alignment (never set here), and
            # the writing mode as vswr_mode numbers it (1 = replace)
            self.intout = [1, self.text_color, 0, 0, 0, self.wrt_mode + 1]
            self.ptsout = self._cell()
            self.contrl2, self.contrl4 = 2, 6
        elif op == V_CONTOURFILL:
            self._contourfill(pts, ints)
        elif op == VSL_ENDS:
            self.line_beg = ints[0] if 0 <= ints[0] <= 2 else LE_SQUARED
            self.line_end = ints[1] if 0 <= ints[1] <= 2 else LE_SQUARED
            self.intout = [self.line_beg, self.line_end]
            self.contrl4 = 2
        elif op == V_GDP:
            self._v_gdp(sub, pts, ints)
        elif op == V_FILLAREA:
            n = min(len(pts) // 2, MAX_POLY)
            self._polygon(pts, n)
        elif op == V_PMARKER:
            self._pmarker(pts)
        elif op == VSM_TYPE:
            v = (ints[0] if MIN_MARK_STYLE <= ints[0] <= MAX_MARK_STYLE
                 else DEF_MARK_STYLE)
            self.mark_index = v - 1
            self.intout[0] = v
            self.contrl4 = 1
        elif op == VSM_HEIGHT:
            h = min(max(pts[1], DEF_MKHT), MAX_MKHT)
            self.mark_height = h
            self.mark_scale = (h + DEF_MKHT // 2) // DEF_MKHT
            self.ptsout = [self.mark_scale * DEF_MKWD,
                           self.mark_scale * DEF_MKHT, 0]
            self.contrl2 = 1
        elif op == VSM_COLOR:
            v = ints[0] if 0 <= ints[0] <= 15 else 1
            self.mark_color = v
            self.intout[0] = v
            self.contrl4 = 1
        elif op == VQL_ATTRIBUTES:
            self.intout = [self.line_index, self.line_color, self.wrt_mode + 1]
            self.ptsout = [self.line_width, 0, 0]
            self.contrl2, self.contrl4 = 1, 3
        elif op == VQM_ATTRIBUTES:
            # the donor answers with mark_index, one less than the type; a
            # caller that feeds the answer back must get the same marker
            self.intout = [self.mark_index + 1, self.mark_color,
                           self.wrt_mode + 1]
            self.ptsout = [0, self.mark_height, 0]
            self.contrl2, self.contrl4 = 1, 3
        elif op == VQF_ATTRIBUTES:
            self.intout = [self.fill_style, self.fill_color,
                           self.fill_index + 1, self.wrt_mode + 1,
                           self.fill_per]
            self.contrl4 = 5
        elif op == VSF_PERIMETER:
            self.fill_per = 1 if ints[0] else 0
            self.intout[0] = self.fill_per
            self.contrl4 = 1
        elif op == VST_ROTATION:
            self.intout[0] = 0
            self.contrl4 = 1
        elif op == V_GET_PIXEL:
            x, y = pts[0], pts[1]
            hw = self.dev.pixel(x, y)
            self.intout = [hw, self.dev.pen_of(hw)]
            self.contrl4 = 2
        elif op == VS_COLOR:
            # one palette entry, in the VDI's thousandths
            i = ints[0]
            if 0 <= i <= 15:
                for k in range(3):
                    v = ints[k + 1]
                    self.pal_req[i][k] = 0 if v < 0 else 1000 if v > 1000 else v
                self.dev.palette_one(i, [col_to_hw(ints[k + 1])
                                         for k in range(3)])
        elif op == VQ_COLOR:
            i = ints[0]
            if not 0 <= i <= 15:
                self.intout = [-1, 0, 0, 0]
            elif ints[1]:               # what the DAC made of it
                self.intout = [i] + [hw_to_col(col_to_hw(self.pal_req[i][k]))
                                     for k in range(3)]
            else:                       # what was asked for
                self.intout = [i] + list(self.pal_req[i])
            self.contrl4 = 4
        elif op == VST_ALIGNMENT:
            self.h_align = ints[0] if TA_LEFT <= ints[0] <= TA_RIGHT else TA_LEFT
            self.v_align = ints[1] if TA_BASE <= ints[1] <= TA_TOP else TA_BASE
            self.intout = [self.h_align, self.v_align]
            self.contrl4 = 2
        elif op == VST_EFFECTS:
            # what was APPLIED, which is not always what was asked for
            self.text_effects = ints[0] & TXT_DONE
            self.intout[0] = self.text_effects
            self.contrl4 = 1
        elif op == VST_POINT:
            self.intout[0] = self.dev.font_point
            self.ptsout = self._cell()
            self.contrl2, self.contrl4 = 2, 1
        elif op == VQT_EXTENT:
            w = (len(ints) * self.dev.font_w
                 + (1 if self.text_effects & TXT_THICKEN else 0))
            self.ptsout = [0, 0, w, 0, w, self.dev.font_h, 0, self.dev.font_h]
            self.contrl2 = 4
        elif op == VQT_WIDTH:
            # three points, and the deltas are a point apart: [0] the
            # cell, [2] the left delta, [4] the right one
            self.intout[0] = ints[0]
            self.ptsout = [self.dev.font_w, 0, 0, 0, 0, 0]
            self.contrl2, self.contrl4 = 3, 1
        elif op == VST_FONT:
            # the face now drawn with: the system's, or the loaded one when
            # its id is asked for (src/vdi/font.c's vdi_font_select)
            got = ints[0] if (self.font_file and ints[0] == self.font_id
                              and ints[0] != FONT_ID_SYS) else FONT_ID_SYS
            self.font = self.font_file if got != FONT_ID_SYS else FONT
            self.intout[0] = got
            self.contrl4 = 1
        elif op == VST_LOAD_FONTS:
            # SYSTEM.FNT, if the disk the gate built has one: the model is
            # told what that file holds (VDI.load_font)
            self.font = self.font_file or FONT
            self.intout[0] = 1 if self.font_file else 0
            self.contrl4 = 1
        elif op == VST_UNLOAD_FONTS:
            self.font = FONT
        elif op == VQT_NAME:
            loaded = self.font_file and ints[0] == FONT_LOADED
            name = self.font_name if loaded else FONT_SYSNAME
            self.intout = [self.font_id if loaded else FONT_ID_SYS]
            self.intout += [ord(c) for c in name[:32]]
            self.intout += [0] * (33 - len(self.intout))
            self.contrl4 = 33
        elif op == VEX_TIMV:
            self.intout[0] = 20          # 50 Hz PAL frame, in ms
            self.contrl4 = 1
        elif op == VSL_UDSTY:
            self.ud_ls = ints[0] & 0xFFFF
        elif op == VSC_FORM:
            self.cur_xhot, self.cur_yhot = ints[0], ints[1]
            self.cur_bg, self.cur_fg = ints[3], ints[4]
            self.cur_mask = [ints[5 + i] & 0xFFFF for i in range(16)]
            self.cur_data = [ints[21 + i] & 0xFFFF for i in range(16)]
        elif op == V_SHOW_C:
            if ints and ints[0] != 0:
                if self.cur_hide > 0:
                    self.cur_hide -= 1
            else:
                self.cur_hide = 0
            if self.cur_hide == 0 and not self.cur_drawn:
                self._cursor_show_now()
        elif op == V_HIDE_C:
            if self.cur_hide == 0:
                self._cursor_hide_now()
            self.cur_hide += 1
        elif op == VRT_CPYFM:
            if form:
                self._vrt_cpyfm(pts, ints, form)
        elif op == V_GTEXT:
            self._gtext(pts, ints)
        elif op == V_PLINE:
            for i in range(len(pts) // 2 - 1):
                self._line(pts[i * 2], pts[i * 2 + 1],
                           pts[i * 2 + 2], pts[i * 2 + 3])
            if LE_ARROWED in (self.line_beg, self.line_end):
                self._line_ends(list(pts), len(pts) // 2)
        elif op == VSL_TYPE:
            self.line_index = ints[0] if 1 <= ints[0] <= 7 else 1
            self.intout[0] = self.line_index
            self.contrl4 = 1
        elif op == VSL_COLOR:
            self.line_color = ints[0] if 0 <= ints[0] <= 15 else 1
            self.intout[0] = self.line_color
            self.contrl4 = 1
        elif op == VSF_INTERIOR:
            self.fill_style = ints[0] if 0 <= ints[0] <= 4 else FIS_HOLLOW
            self.intout[0] = self.fill_style
            self.contrl4 = 1
        elif op == VSF_STYLE:
            # The range depends on the interior in force: 1..24 for patterns,
            # 1..12 for hatches; anything else becomes 1.  Stored minus one.
            top = MAX_FILL_PATTERN if self.fill_style == FIS_PATTERN else MAX_FILL_HATCH
            fi = ints[0] if 1 <= ints[0] <= top else 1
            self.fill_index = fi - 1
            self.intout[0] = fi
            self.contrl4 = 1
        elif op == VSF_UDPAT:
            # Only a 16-word (single-plane) pattern is accepted; anything
            # else leaves the old one alone.  Nothing is returned.
            if len(ints) == 16:
                self.ud_patrn = [w & 0xFFFF for w in ints]
        elif op == VSF_COLOR:
            self.fill_color = ints[0] if 0 <= ints[0] <= 15 else 1
            self.intout[0] = self.fill_color
            self.contrl4 = 1
        elif op == VST_COLOR:
            self.text_color = ints[0] if 0 <= ints[0] <= 15 else 1
            self.intout[0] = self.text_color
            self.contrl4 = 1
        elif op == VSWR_MODE:
            self.wrt_mode = (ints[0] - 1) if 1 <= ints[0] <= 4 else 0
            self.intout[0] = self.wrt_mode + 1
            self.contrl4 = 1
        elif op == V_STRING:
            # one key per call; contrl[4] = 0 says there was none
            if self.keys:
                self.intout[0] = self.keys.pop(0)
                self.contrl4 = 1
        elif op == VQ_KEY_S:
            self.intout[0] = self.key_mods
            self.contrl4 = 1
        # everything else is a documented no-op on this driver

    def input_poll(self, tick=False):
        """vdi_input_poll(): the cursor follows the pointer, then motion
        every pass, the button vector on a change, the timer vector once
        per frame.  The key poll has no counterpart here -- a plan step
        puts its key straight in `keys`.  `tick` says this pass is the
        first of a frame, where VCOUNT's wrap lands."""
        self._cursor_move()
        if self.vec_motv:
            self.vec_motv()
        if self.buttons != self.last_buttons:
            self.last_buttons = self.buttons
            if self.vec_butv:
                self.vec_butv()
        if tick and self.vec_timv:
            self.vec_timv()

    def result(self):
        """The record src/m3_vdi.c writes for the last call, with
        the same masking as the target: only the declared words count."""
        return record(self.contrl2, self.contrl4, self.intout, self.ptsout)

    def run(self, script):
        self.results = []
        for rec in script:
            self.call(rec[0],
                      rec[1] if len(rec) > 1 else (),
                      rec[2] if len(rec) > 2 else (),
                      rec[3] if len(rec) > 3 else None,
                      sub=rec[4] if len(rec) > 4 else 0)
            self.results.append(self.result())

    def to_rgb(self):
        return self.dev.to_rgb()

    def screen_key(self):
        """A fingerprint of the visible screen, for telling whether a turn
        of the AES drew anything (aesref's held-button rule)."""
        return self.dev.key()


# vbxeref owns the VRAM map now: devref's Vbxe device reads it too, and
# two copies of a lookup into vbxe.h is exactly how a model drifts.
vram_symbol = vbxeref.vram_symbol


class VramForm:
    """An MFDB whose fd_addr is a VRAM address -- the AES's save buffer
    (vbxe.h VR_SAVE), which bb_save and bb_restore copy the screen to and
    from.  mfdb_addr is where the harness staged the 20-byte MFDB on the
    target, for encode(); the reference reads the form's fields directly."""

    def __init__(self, addr, w, h, wdwidth, planes=4, mfdb_addr=0):
        self.addr, self.w, self.h = addr, w, h
        self.wdwidth, self.planes, self.mfdb_addr = wdwidth, planes, mfdb_addr

    @classmethod
    def save_buffer(cls, mfdb_addr=0, w=SCR_W, h=SCR_H):
        """The AES's: a whole screen at VR_SAVE, laid out like the screen
        -- so it is the screen's width, and a caller drawing at another
        one has to say so.  VR_SAVE itself does not move: the VRAM map is
        laid out for the widest overlay whatever is being shown
        (src/vbxe/vbxe.h)."""
        return cls(vram_symbol("VR_SAVE"), w, h, w // 16, 4, mfdb_addr)

    @property
    def stride(self):
        return self.wdwidth * 2 * self.planes

    def pack(self):
        return pack_mfdb(self.addr, self.w, self.h, self.wdwidth, self.planes)


def encode(script, mfdb_addr=0, screen_mfdb=0):
    """Serialise a script into the WORD stream src/m3_vdi.c expects.

    A record carrying a `form` gets mfdb_addr planted in contrl[7..8], which is
    where the harness has staged the MFDB on the target.  A vro_cpyfm record's
    form is the (source, destination) pair of VramForm-or-None, planted in
    contrl[7..8] and contrl[9..10]: None becomes screen_mfdb, the address of
    a staged MFDB with fd_addr 0 (or 0, which the driver takes as the screen).
    """
    def addr_of(f):
        return screen_mfdb if f is None else f.mfdb_addr

    out = []
    for rec in script:
        op = rec[0]
        pts = list(rec[1]) if len(rec) > 1 else []
        ints = list(rec[2]) if len(rec) > 2 else []
        form = rec[3] if len(rec) > 3 else None
        sub = rec[4] if len(rec) > 4 else 0      # contrl[5]
        if len(pts) & 1:
            # ptsin is POINTS: an odd count would declare one point fewer
            # than it writes and slide the rest of the stream by a word,
            # which the runner then reads as a further call.
            raise ValueError(f"op {op}: {len(pts)} ptsin words, not a whole "
                             f"number of points")
        c7 = c8 = c9 = c10 = 0
        if form and op == VRO_CPYFM:
            c7, c9 = addr_of(form[0]), addr_of(form[1])
        elif form:
            c7 = mfdb_addr & 0xFFFF
            c8 = (mfdb_addr >> 16) & 0xFFFF
        out += [op, len(pts) // 2, len(ints), c7, c8, c9, c10, sub]
        out += pts
        out += ints
    out.append(0)
    return out


def decode_quad(prev, now):
    """Reference for ptr_decode_quad() in src/vdi/pointer.c.

    Classic 2-bit Gray-code table.  The four two-step ("impossible") entries
    are 0 on purpose: on a missed sample it is better to drop motion than to
    invent it in the wrong direction.
    """
    table = (0, +1, -1, 0,
             -1, 0, 0, +1,
             +1, 0, 0, -1,
             0, -1, +1, 0)
    return table[((prev & 3) << 2) | (now & 3)]


def decode_tb(prev, now):
    """Reference for ptr_decode_tb() in src/vdi/pointer.c: the CX80 trak-ball
    in trak-ball mode, which is not quadrature.  Each axis has a direction
    line (bit 1 of the pair) and a pulse line (bit 0) that toggles once per
    count; a count is a change on the pulse line, and its sign is the
    direction line AS SAMPLED WITH THE EDGE -- Altirra's model changes the
    two in the same update, so the previous sample's direction is stale.
    High is + on the port's active-low lines.
    """
    if ((prev ^ now) & 1) == 0:
        return 0
    return +1 if now & 2 else -1


def xem1_valid(pot):
    """A mouSTer XEM1 pot reading is 64..191: bit 6 and bit 7 differ."""
    return (((pot >> 1) ^ pot) & 0x40) != 0


def decode_xem1(old, now):
    """Reference for ptr_decode_xem1() in src/vdi/pointer.c: the movement
    between two XEM1 readings, and the reading to measure the next from.

    This is the firmware's sample driver (Mad-Pascal samples/a8/mouSTer/
    vbl.asm, calcDX) followed instruction by instruction rather than a
    formula of my own, so that what the C is checked against is what the
    device's author wrote: the 7-bit difference, sign-extended from bit 6
    by the rol/eor/and/eor trick, halved toward zero by cmp/ror/adc, and a
    reading that halves to nothing left as the reference for next time.
    """
    a = (now - old) & 0xFF                      # txa; sec; sbc oldX
    if a == 0:                                  # beq endCalcX
        return 0, old
    t = a                                       # sta @+
    a = (a << 1) & 0xFF                         # rol (the carry in is masked out below)
    a ^= t                                      # eor @: -- bit 7 = d6 ^ d7
    a &= 0x80                                   # and #$80
    a ^= t                                      # eor @- -- bit 7 := d6
    c = 1 if a >= 0x80 else 0                   # cmp #$80
    c, a = a & 1, (a >> 1) | (c << 7)           # ror
    if a & 0x80:                                # bpl @+
        a = (a + c) & 0xFF                      # adc #0
    if a == 0:                                  # @ beq endcalcX
        return 0, old
    return (a - 256 if a & 0x80 else a), now    # stx oldX


def pack_mfdb(bits_addr, w, h, wdwidth, planes=1):
    """The 20-byte MFDB the target reads, little-endian."""
    import struct
    return struct.pack("<Ihhhhhhhh", bits_addr, w, h, wdwidth, 0, planes,
                       0, 0, 0)
